language: csharp
os: osx
mono: none
dotnet: 2.0.0
dist: trusty
env:
  matrix:
  - NODE_VERSION="8.5.0"
  global:
  - secure: ljQ8VoDOyBRvPTFSxTsKV+ERf6uZqP5U9SEfYW5EymBRQSokZKKowY7gkptu/1DkFl0EXOpIR6psX00No+bFDuRB/tug5upJlYNE9BPCzP77fFz1WxfbgyxEC7FvpViUP4mQW6w3lScPZI/bx6sBGWdS5hcLfbyzIow3HpmF2gmqaUzpxLokeCLgVXMz0j29gkmfiJwtDUmtl8vg/rV2mdA384kxCpXammWN/dXXDsBgPPLBHt1/yaJhX7oSjBj6ErxF6wUeiac4U9wUHnvyBvO1Ahht9Zzq8OZfafaj1EAnl7e7hzGDYdwaKZT17Dr7PPm1pUCm+gGTZleEhO1OJnIR09zEyk/uXdMc7ez0qATr0I4Wb3iXWpBYvZ6JzGBrVeEI3Xckzp/Two8t4OKV8ZRV8q9TgnfU8KpKQR2lcl+iHIiIi3NnxAg40TXsTTjWP35U3y5NFZBIfxQg1kj8j/PLSbl60PQA+116H+hXVPSOLaxDMVldlZeN7FNniSfT4j7agj2C6ldIg10qfI6DVtMU04v6YL5WdUkELOI4dpdp5ewJgUkf7yTxQPaqn95aDKuriPhm+YXzIkfuyOeefT1YOBF3aEzzbJ9f7f2A9bOezhlzP+PIGoqgOAXIMSf6WiG0Iu6KemB8v+LVjVB7Q7tkEfqr3vChlL3a76B5enM=
addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod
        trusty main
      key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5
before_install:
- wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
- source ~/.nvm/nvm.sh
- nvm install 8
- node --version
# - chmod +x build_mac.sh
# - chmod +x build_linux.sh
script:
- cd src
- cd api
- cd api
- dotnet restore
- dotnet publish --configuration release --self-contained -r win-x86 --output ../bin/dist/win
- dotnet publish --configuration release --self-contained -r linux-x64 --output ../bin/dist/linux64
- dotnet publish --configuration release --self-contained -r osx-x64 --output ../bin/dist/osx
- cd ..
- cd ..
- cd app
- sudo apt install icnsutils
- echo $TRAVIS_BUILD_NUMBER
- npm version 1.1.$TRAVIS_BUILD_NUMBER -m 'v1.1.$TRAVIS_BUILD_NUMBER'
- npm install
- npm run electron:macnpm run electron:windows
- npm run electron:linux
- npm run electron:mac
# - "./build_linux.sh"
# - "./build_mac.sh"
deploy:
  provider: releases
  api_key:
    secure: VlUR37gZyaCqCTyaoHWuZ+Dxoy12k/DEpK5xoXoqPYOewLXoYh47lguPGER9vP9r7FaJCQLlQxJ1cZOgiJ8r7zstsEVL2FGMWiM1W+sHLPoBa5NXmximbDRTNBYrUc8+PAncdGdfnlo4AWR0/+wbIQJ8/cg/ri11BCOkpxe4ZT9jgp6Pd1Lsiq9V2Phqoaz/g+hxxLPfMCzkMSWo5ya53S4tr5DGFRRm/8UlhdU4j4wBDEXLiWNP5erTFvJRamcltjdkBBPMoVNVR5BqF7Vu+Lm2CzJZsIS5pn0/FLirKV8DuzZoqn2J1Ia8bU9AadjzzSgtmGbMk8pJrZloVOv2m/A7LNF1s3smRQrtHcfz/Byna66zwvfnjezR3tEE8oHGjRG+xoM1rzya1j5uUbH6SUcf2Rbm/zNVB74gFJOsMJEYsYNRWzbrdT/1SBQiOfMMO5i5jokPAS4GC6dikbg/G1CPhNUjQuWfjl8O/k2ItGNSZ/LEVvGjYXaH3vYkNLhU/CrGDplIaTL2Gw0INILHGSNbWHPZVRhImT2RAjIEQqPl3tYOgZPB9YHYl52TpUbpxBBLVhgr63YvBDHSU1IA4tegrwWL3JXDPcfljep2uVNs9gSKdeQy+rxuBJKicoQAJ0/+5qpXrnDK15Q4uY21zqycqZbPfui05yQdGmifrHA=
  file:
  - "./dist/*.dmg"
  - "./dist/*.AppImage"
  - "./dist/*.deb"
  skip_cleanup: true
  on:
    branch: master
