version: 1.0.{build}
image: Visual Studio 2017 Preview
skip_tags: true
install:
- ps: Install-Product node 8.5.0 x64
dotnet_csproj:
    
  patch: true

  file: '**\*.csproj'

  version: '{version}'

  package_version: '{version}'

  assembly_version: '{version}'

  file_version: '{version}'

  informational_version: '{version}'

build_script:

- cmd: >-

    cd src

    cd api

    cd api

    dotnet restore
    
    dotnet publish --configuration release --self-contained -r win10-x64 --output ../bin/dist/win
    
    REM dotnet publish --configuration release --self-contained -r osx-x64 --output ../bin/dist/osx

    REM dotnet publish --configuration release --self-contained -r linux-x64 --output ../bin/dist/linux64
    
    cd ..
    
    cd ..
    
    cd app
    
    npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION
    
    npm install
    
    npm run electron:windows

test: off
artifacts:

- path: .\dist\*.exe

  name: WindowsInstaller
 
deploy:
    provider: GitHub
    release: inshapardaz-desktop-v$(APPVEYOR_BUILD_VERSION)
    description: 'Desktop App release'
    auth_token:
        secure: 9pGUKf/Hgy5/M1jMlfZtScSRwXspsTBc00gHihlg7P6zb66NDIQekq7D0usaiogk
    artifact: WindowsInstaller
    draft: false
    prerelease: false
    on:
        branch: master # release from master branch only