namespace Inshapardaz.Desktop.Common.Models
{
    public enum LanguageType
    {
        None,
        Unknown,
        Urdu,
        Sanskrit,
        Persian,
        Arabic,
        Turkish,
        English,
        French,
        Prakrit,
        Latin,
        Punjabi,
        Greek,
        Hebrew,
        Portuguese,
        Italian,
        Spanish,
        Chinese,
        Japanese,
        Sindhi,
        German,
        Local,
        Syriac,
        Avestan
    }
}